### ISSUE TITLE
Pagination funktioniert nicht in Listenmodulen mit aktiviertem Atorenfilter

### ISSUE THREAD

**Issue by jommbee** [inspiredminds/contao-author-news#1]
Hallo,
erstmal die **Eckdaten der Installation**:
- Contao 4.4.40
- contao-author-news Version 1.0.0
- Sonst keine Erweiterungen.
- Newsarchiv mit 5 News
- Listenmodul mit Pagination (Elemente pro Seite: 3, Gesamtzahl: 0 )

**In dieser Einstellung klappt alles wie es soll.**

Dann **Filter für Author aktiviert, Standard Autor ausgewählt**:

Es werden weiter zwei Seiten in der Pagination angezeigt. Allerdings werden auf beiden Seiten alle News gezeigt (5 Stück statt 3).

Gleicher Effekt wenn ich z.B. Elemente pro Seite 1 einstelle. 5 Seiten in der Pagination, alle mit den 5 gleichen News.
Parameter der Pagination im URL: Beispiel: /?page_n1=4

Grüße

**Comment by fritzmg** [comment]
Ja, hab den Fehler gefunden :). Bitte mal `dev-master` testen.

**Comment by jommbee** [comment]
Funktioniert. Danke!

**Comment by fritzmg** [comment]
Ist mit 1.0.1 veröffentlicht.
