### ISSUE TITLE
Felder werden im Newsmodul nicht angezeigt (Contao 4.9)

### ISSUE THREAD

**Issue by jommbee** [inspiredminds/contao-author-news#2]
Hallo,

leider werden die nötigen Felder zur Konfiguration im Newslisten-Modul nicht mehr angezeigt. 

Ein Behelf über über den PaletteManipulator hilft erstmal:

```
<?php

// contao/dca/tl_module.php
use Contao\CoreBundle\DataContainer\PaletteManipulator;


PaletteManipulator::create()
    ->addField('authorFilter', 'config_legend', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('newslist', 'tl_module')
;
```
Reicht so schon aus die Funktion wieder sichtbar zu machen und zu nutzen.

**Comment by fritzmg** [comment]
Fixed in 8a5a60c.
