### ISSUE TITLE
Frontend Ausgabe erfolgt ohne Filterung

### ISSUE THREAD

**Issue by 108g** [inspiredminds/contao-author-news#4]
Hallo,

habe soeben inspiredminds/contao-author-news unter Contao 4.9.16 installiert. Zusätzlich ist news_categories im Einsatz. Das Modul lässt sich wie beschrieben konfigurieren. Jedoch bleibt die FE Ausgabe vom Parameter oder auch festgelegten Standard-Autor leider unberührt. Es werden immer alle News-Einträge ausgegeben. Es erfolgt keine Filterung. Installation verlief erfolgreich und fehlerfrei. Cache wurde gelehrt. Der Debug-Modus zeigt keine Fehler.

Danke!

**Comment by fritzmg** [comment]
Are you using `codefog/contao-news_categories`? If yes, which version?

**Comment by 108g** [comment]
yes i'm using the version 3.4.8 of `codefog/contao-news_categories`

**Comment by fritzmg** [comment]
Ah ok, then this is a duplicate of #3
